version: "3"
services:
  _home:
    image: nginx:stable-alpine
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${DOMAIN_NAME_5},www.${DOMAIN_NAME_5},${DOMAIN_NAME_1},www.${DOMAIN_NAME_1}
      - LETSENCRYPT_HOST=${DOMAIN_NAME_5},www.${DOMAIN_NAME_5},${DOMAIN_NAME_1},www.${DOMAIN_NAME_1}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=${DEFAULT_EMAIL}
      - LETSENCRYPT_TEST=false
      - LETSENCRYPT_RESTART_CONTAINER=true
      - DEBUG=0
    volumes:
      - ${DOCKER_WEB}/Home:/usr/share/nginx/html:ro
      - conf:/etc/nginx/conf.d
      - certs:/etc/nginx/certs
    restart: unless-stopped
  _blog:
    image: nginx:stable-alpine
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=blog.${DOMAIN_NAME_5},www.blog.${DOMAIN_NAME_5},blog.${DOMAIN_NAME_1},www.blog.${DOMAIN_NAME_1}
      - LETSENCRYPT_HOST=blog.${DOMAIN_NAME_5},www.blog.${DOMAIN_NAME_5},blog.${DOMAIN_NAME_1},www.blog.${DOMAIN_NAME_1}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=${DEFAULT_EMAIL}
      - LETSENCRYPT_TEST=false
      - LETSENCRYPT_RESTART_CONTAINER=true
      - DEBUG=0
    volumes:
      - ${DOCKER_WEB}/Blog:/usr/share/nginx/html:ro
      - conf:/etc/nginx/conf.d
      - certs:/etc/nginx/certs
    restart: unless-stopped

networks:
  default:
    external:
      name: ${NETWORK}

volumes:
  conf:
  certs:
    # logs:
    # reports:
