version: "3.8"
services:
  nginx-alpine-web:
    # image: httpd:alpine
    image: nginxinc/nginx-unprivileged:stable-alpine
    container_name: web_wagui
    # expose:
      - 80
      - 443
    env_file:
      - .env
    environment:
      - "VIRTUAL_HOST=.${DOMAIN_NAME_1}"
      # - "VIRTUAL_HOST=.${DOMAIN_NAME_1}, .${DOMAIN_NAME_2}"
      - "LETSENCRYPT_HOST=.${DOMAIN_NAME_1}"
      - "LETSENCRYPT_EMAIL=${DEFAULT_EMAIL}"
      # - "LETSENCRYPT_HOST=subdomain.yourdomain.tld"
      - "NETWORK=${NETWORK}"
      # - "VIRTUAL_PORT=8080"
    # volumes:
      # - "${CONTAINER_DIR}/html:/usr/share/nginx/html:ro"
    restart: unless-stopped
    networks:
      - default
  
networks:
  default:
    external:
      name: ${NETWORK}

#     - LETSENCRYPT_HOST=domain.com
# 'ro' = read only