version: "3.8"
services:
  nginx-alpine-web:
    image: nginx:alpine
    container_name: web_wagui
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    environment:
      - "VIRTUAL_HOST:${VULTR_IP}.1234"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "${CONTAINER_DIR}/web_files:/usr/share/nginx/html:ro"
    restart: unless-stopped
  
networks:
  default:
    external:
      name: nginx-proxy