version: "3.8"
services:
  nginx-alpine-web:
    image: nginx:alpine
    container_name: web_wagui
    expose:
      - 80
    env_file:
      - .env
    environment:
      - "VIRTUAL_HOST=wagui.${DOMAIN_NAME}"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "${CONTAINER_DIR}/WebFiles:/usr/share/nginx/html:ro"
    restart: unless-stopped
  
networks:
  default:
    external:
      name: nginx-proxy