version: "3.8"
services:
  nginx-alpine-web:
    image: nginx:alpine
    container_name: web_wagui
    expose:
      - 80
    env_file:
      - .env
    environment:
      - "VIRTUAL_HOST=.${DOMAIN_NAME_2}"
    volumes:
      - "${CONTAINER_DIR}/html:/usr/share/nginx/html:ro"
    restart: unless-stopped
  
networks:
  default:
    external:
      name: nginx-proxy

#     - LETSENCRYPT_HOST=domain.com
