version: "3.8"
services:
  nginx-alpine-web:
    image: nginxinc/nginx-unprivileged:stable-alpine
    container_name: web_wagui
    expose:
      - 8080
    env_file:
      - .env
    environment:
      - "VIRTUAL_HOST=.${DOMAIN_NAME_1}, .${DOMAIN_NAME_2}"
      - "VIRTUAL_HOST=.${DOMAIN_NAME_1}, .${DOMAIN_NAME_2}"
      - "LETSENCRYPT_HOST=.${DOMAIN_NAME_1}, .${DOMAIN_NAME_2}"
      # - "LETSENCRYPT_HOST=subdomain.yourdomain.tld"
      # - "VIRTUAL_PORT=8080"
    volumes:
      - "${CONTAINER_DIR}/html:/usr/share/nginx/html:ro"
    restart: unless-stopped
  
networks:
  default:
    external:
      name: nginx-proxy

#     - LETSENCRYPT_HOST=domain.com
# 'ro' = read only