version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxi
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro 
    restart: unless-stopped
          
networks:
  default:
    external:
      name: nginx-proxy
# command: "sh -c 'echo \"server_tokens off;\" > /etc/nginx/conf.d/my_proxy.conf; forego start -r'"

#image: nginx:stable-alpine